### PR TITLE
Use kotlin for generated bindings

### PR DESCRIPTION
**Pull request by stevenosse**

### CODE REVIEW

**Comment by Tiska** [comment]
nice pr :) could you update it so we can merge it ? also we shoud make a new release :)

**Comment by stevenosse** [comment]
> nice pr :) could you update it so we can merge it ? also we shoud make a new release :)

Hello
What do you mean by "update" ? ^^'

**Comment by Tiska** [comment]
Rebase 😁

**Comment by stevsct** [comment]
The branch is up to date

**Review by Tiska — APPROVED** [review]

**Pull request merged**
